<?php

return [
    'Auditoria' => [
        'ocorrencias' => [
            1 => 'Logon no sistema',
            2 => 'Troca de senha',
            3 => 'Bloqueio de IP',
            4 => 'Suspensão da conta',
            5 => 'Limpeza de cache e sessão',
            6 => 'Acesso suspeito',
            7 => 'Acesso bloqueado',
            8 => 'Logoff no sistema',
            9 => 'Impressão de documento',
            10 => 'Inclusão do usuário',
            11 => 'Alteração do usuário',
            12 => 'Exclusão do usuário',
            13 => 'Inclusão do grupo de usuário',
            14 => 'Alteração do grupo de usuário',
            15 => 'Exclusão do grupo de usuário',
            16 => 'Adicão do registro do firewall lista negra',
            17 => 'Adicão do registro do firewall lista branca',
            18 => 'Edição do registro do firewall',
            19 => 'Exclusão do registro do firewall',
            20 => 'Liberação de usuário suspenso',
            21 => 'Inclusão da legislação',
            22 => 'Alteração da legislação',
            23 => 'Exclusão da legislação',
            24 => 'Inclusão da licitação',
            25 => 'Alteração da licitação',
            26 => 'Exclusão da licitação',
            27 => 'Inclusão da notícia',
            28 => 'Alteração da notícia',
            29 => 'Exclusão da notícia',
            30 => 'Inclusão da secretaria',
            31 => 'Alteração da secretaria',
            32 => 'Exclusão da secretaria',
            33 => 'Inclusão de banner',
            34 => 'Alteração de banner',
            35 => 'Exclusão de banner',
            36 => 'Edição de perfil do usuário',
            37 => 'Mudança de senha',
            38 => 'Visualização do registro de auditoria',
            39 => 'Impressão da trilha de auditoria',
            40 => 'Exclusão do registro de auditoria',
            41 => 'Envio de mensagem interna do sistema',
            42 => 'Mensagem excluída da caixa de entrada',
            43 => 'Mensagem enviada excluída',
            44 => 'Exclusão física da mensagem',
            45 => 'Aceite de manifestação',
            46 => 'Recusa de manifestação',
            47 => 'Resposta de manifestação',
            48 => 'Conclusão de manifestação',
            49 => 'Fechamento da manifestação',
            50 => 'Alteração de status de manifestação',
            51 => 'Inclusão de Feriado',
            52 => 'Alteração de Feriado',
            53 => 'Exclusão de Feriado'
        ]
    ]
];
